name: docker-build-push
description: docker building and publishing

inputs:
    push:
        description: "Push the image to the registry"
        required: false
        default: false
    name:
        description: "The name of the package to build"
        required: true
    version:
        description: "The version of the package to build"
        required: true
    registry:
        description: "The registry to push the image to"
        required: false
        default: "juftin"
    latest:
        description: "Tag the image as latest"
        required: false
        default: true
    username:
        description: "The username for the registry"
        required: false
        default: ""
    password:
        description: "The password for the registry"
        required: false
        default: ""
    context:
        description: "The context to use for the build"
        required: false
        default: "."
    load:
        description: "Load the image into docker after building"
        required: false
        default: false

runs:
    using: composite
    steps:
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Login to DockerHub
          if: inputs.username && inputs.password
          uses: docker/login-action@v2
          with:
              username: ${{ inputs.username }}
              password: ${{ inputs.password }}
        - name: Docker Image Building and Publishing
          if: ${{ !inputs.latest }}
          uses: docker/build-push-action@v5
          with:
              push: ${{ inputs.push }}
              tags: ${{ inputs.registry }}/${{ inputs.name }}:${{ inputs.version }}
              context: ${{ inputs.context }}
              load: ${{ inputs.load }}
        - name: Docker Image Building and Publishing (latest)
          if: ${{ inputs.latest }}
          uses: docker/build-push-action@v5
          with:
              push: ${{ inputs.push }}
              tags: ${{ inputs.registry }}/${{ inputs.name }}:${{ inputs.version }},${{ inputs.registry }}/${{ inputs.name }}:latest
              context: ${{ inputs.context }}
              load: ${{ inputs.load }}
