name: hatch-setup
description: GitHub composite workflow to setup hatch + python

inputs:
    python_version:
        description: Python Version to install
        required: true
    create_env:
        description: Create a new virtual environment
        default: ""
    additional_dependencies:
        description: Additional dependencies to install
        default: ""
    shell:
        description: Shell to use for running commands
        required: false
        default: "bash"

runs:
    using: composite
    steps:
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
              python-version: ${{ inputs.python_version }}
        - name: Install Additional Dependencies
          if: inputs.additional_dependencies != ''
          run: |
              python -m pip install -q ${{ inputs.additional_dependencies }}
          shell: ${{ inputs.shell }}
        - name: Install Hatch
          shell: ${{ inputs.shell }}
          run: |
              python -m pip install --upgrade pip
              python -m pip install -q hatch pre-commit
              hatch --version
        - name: Create Virtual Environment
          if: inputs.create_env != ''
          run: |
              hatch env create ${{ inputs.create_env }}
          shell: ${{ inputs.shell }}
