name: Docker CI/CD

on:
    pull_request:
        branches: ["**"]

jobs:
    docker-ci-test:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Github Workspace
              uses: actions/checkout@v4
            - name: Setup Hatch
              uses: ./hatch-setup
              with:
                  python_version: "3.11"
            - name: Get Package Info
              uses: ./hatch-version
              id: package
            - name: Docker Image Workflow
              uses: ./docker-build-push
              with:
                  registry: juftin
                  push: false
                  name: ${{ steps.package.outputs.name }}
                  version: ${{ steps.package.outputs.version }}
                  context: .docs/
