name: Release
on:
    push:
        branches:
            - main
            - next
            - beta
            - alpha
            - "*.x"
jobs:
    release:
        name: github-release
        if: github.repository_owner == 'juftin'
        runs-on: ubuntu-latest
        permissions:
            contents: write
            issues: write
            pull-requests: write
        steps:
            - name: semantic-release
              uses: juftin/actions/e2e/semantic-release@v1
    github-pages-publish:
        runs-on: ubuntu-latest
        needs: release
        if: github.ref == 'refs/heads/main' && github.repository_owner == 'juftin'
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: github-pages
              id: deployment
              uses: juftin/actions/e2e/github-pages@v1
