name: Release
on:
    push:
        branches:
            - main
            - next
            - beta
            - alpha
            - "*.x"
jobs:
    release:
        name: github-release
        if: github.repository_owner == 'juftin'
        runs-on: ubuntu-latest
        permissions:
            contents: write
            issues: write
            pull-requests: write
        steps:
            - name: Set up Github Workspace
              uses: juftin/actions/e2e/semantic-release@v1

    github-pages-publish:
        runs-on: ubuntu-latest
        needs: release
        if: github.ref == 'refs/heads/main' && github.repository_owner == 'juftin'
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Set up Github Workspace
              uses: actions/checkout@v4
            - name: Setup Hatch
              uses: ./hatch-setup
              with:
                  python_version: "3.11"
            - name: Build Docs
              uses: ./hatch-docs
            - name: Publish Docs
              uses: ./github-pages
              id: deployment
